### create a new user

POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "walliz@gmail.com",
    "password": "Password@123"
}

### sign in an existing user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "walliz@gmail.com",
    "password": "Password@123"
}

### Get the currrently login user

GET http://localhost:3000/auth/whoami

### signout the currrently login user

POST  http://localhost:3000/auth/signout


### find a particular user with given ID

GET  http://localhost:3000/auth/5


### find all users 

GET  http://localhost:3000/auth?email=wallace@gmail.com


### Delete user

DELETE   http://localhost:3000/auth/9

### Update user

PATCH  http://localhost:3000/auth/5
content-type: application/json

{
    
    "password": "ppassword@123updated"
}